//view-source:http://gymkhana.iitb.ac.in/~sports/index.php?r=gc/tally

 <div class="content gc">
    	<table class="table table-bordered">
    		<thead>
    			<th>GC</th>
    			<th>H1</th>
    			<th>H2</th>
    			<th>H3</th>
    			<th>H4</th>
    			<th>H5</th>
    			<th>H6</th>
    			<th>H7</th>
    			<th>H8</th>
    			<th>H9</th>
    			<th>H12</th>
    			<th>H13</th>
    			<th>H14</th>
                <th>H15</th>
    			<th>Tansa</th>
    			<th></th>
    			<th>H10</th>
    			<th>H11</th>
    		</thead>
    		<tbody>
                                                <tr>
                    <td><b>Swimming<b></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>12</td>
                    <td>5</td>
                    <td>9</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>5</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                                                <tr>
                    <td><b>Table Tennis<b></td>
                    <td>4</td>
                    <td>12</td>
                    <td>6</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>9</td>
                    <td></td>
                    <td></td>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                                                <tr>
                    <td><b>Badminton<b></td>
                    <td></td>
                    <td>12</td>
                    <td></td>
                    <td>9</td>
                    <td></td>
                    <td>6</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>4</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                                                <tr>
                    <td><b>Squash<b></td>
                    <td></td>
                    <td>12</td>
                    <td>4</td>
                    <td></td>
                    <td>6</td>
                    <td>9</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                                                <tr>
                    <td><b>Weightlifting<b></td>
                    <td></td>
                    <td></td>
                    <td>9</td>
                    <td>12</td>
                    <td>4</td>
                    <td></td>
                    <td></td>
                    <td>6</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                                                <tr>
                    <td><b>Chess<b></td>
                    <td>6</td>
                    <td></td>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>4</td>
                    <td></td>
                    <td>2</td>
                    <td></td>
                    <td>9</td>
                    <td></td>
                    <td>12</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                                                <tr>
                    <td><b>Crossy<b></td>
                    <td></td>
                    <td>3</td>
                    <td>4.5</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>6</td>
                    <td></td>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                                                <tr>
                    <td><b>Carrom<b></td>
                    <td>9</td>
                    <td></td>
                    <td></td>
                    <td>6</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>4</td>
                    <td></td>
                    <td>12</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                                                <tr>
                    <td><b>Lawn Tennis<b></td>
                    <td></td>
                    <td>4</td>
                    <td>12</td>
                    <td></td>
                    <td>6</td>
                    <td></td>
                    <td>9</td>
                    <td>2</td>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                                                <tr>
                    <td><b>Kho-Kho<b></td>
                    <td></td>
                    <td></td>
                    <td>12</td>
                    <td>9</td>
                    <td></td>
                    <td></td>
                    <td>6</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>4</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                                                <tr class="total-row">
                    <td>Total</td>
                    <td>19</td>
                    <td>43</td>
                    <td>49.5</td>
                    <td>36</td>
                    <td>16</td>
                    <td>15</td>
                    <td>37</td>
                    <td>26</td>
                    <td>15</td>
                    <td>12</td>
                    <td>15</td>
                    <td>4</td>
                    <td>17</td>
                    <td>0</td>
                    <td></td>
                    <td>0</td>
                    <td>0</td>
                </tr>
    		</tbody>
    	</table>
    </div>
